#!/bin/sh
# - runtime
# - protocol
# - sessions
# - port
# - numactl
# - tune
## iperf is a tool for active measurements of the maximum achievable
## bandwidth on IP networks. It supports tuning of various parameters
## related to timing, protocols, and buffers. For each test
## it reports the bandwidth, loss, and other parameters.

. "$LKP_SRC/lib/sysinfo.sh"

numactl_server=""
numactl_client=""


tune_param()
{
    [ -n "$tune" ] || return

    for kv in $tune; do
        sysctl -w "$kv" > /dev/null
    done
}

[ -n "$tune" ] && tune_param

[ -n "$runtime" ] || runtime=300
[ "$protocol" = udp ] && opt_udp=-u
[ -n "$sessions" ] || sessions=1
[ -n "$port" ] || port=5001
[ "$numactl" = true ] && numactl_server="numactl -C $(($cores_per_node+i))" && numactl_client="numactl -C $((0+i))"

[ -n "$direct_server_ips" ] && server=$direct_server_ips
[ -z "$server" ] && server=127.0.0.1
server=${server%% *}

for i in `seq 1 $sessions`; do
	$numactl_server iperf3 -s -B $server -p $(($port+i-1)) > /dev/null &
done

for i in `seq 1 $sessions`; do
	$numactl_client iperf3 -c $server -p $(($port+i-1)) -i 10 -T $((0+i-1)) -J -t $runtime&
done

echo "$(date +'%F %T') ${client_cmd}" >> $RESULT_ROOT/reproduce.sh
